v: 2.6.0
overrideConfig: false
ie:
    - DS_Store
    - less
    - scss
id:
    - scss
    - .svn
    - .sass-cache
cleanPublic: 'true'
patternStates:
    - inprogress
    - inreview
    - complete
styleGuideExcludes: ''
cacheBusterOn: 'true'
exportDir: ../html
publicDir: public
sourceDir: source
defaultPattern: all
defaultShowPatternInfo: false
ishMinimum: '240'
ishMaximum: '2600'
ishControlsHide:
    - hay
styleguideKit: pattern-lab/styleguidekit-twig-default
styleguideKitPath: vendor/pattern-lab/styleguidekit-twig-default
lineageMatch: '{%([ ]+)?include( |\()[&quot;\&#039;]([A-Za-z0-9-_]+)[&quot;\&#039;](\))?(.*)%}'
lineageMatchKey: 3
patternExtension: twig
twigDebug: true
twigAutoescape: false
twigDefaultDateFormat: ''
twigDefaultIntervalFormat: ''
twigMacroExt: macro.twig
twigFilterExt: filter.php
twigFunctionExt: function.php
twigTagExt: tag.php
twigTestExt: test.php
plugins:
  twigNamespaces:
    enabled: true
    roots: { }
      #- source/_patterns/01-atoms
      #- source/_patterns/02-molecules
      #- source/_patterns/03-organisms
      #- source/_patterns/04-pages
    namespaces:
      atoms:
        paths:
          - source/_patterns/01-atoms/01-list-title
          - source/_patterns/01-atoms/02-list-body
          - source/_patterns/01-atoms/03-list-image
          - source/_patterns/01-atoms/04-blog-tag
          - source/_patterns/01-atoms/05-list-posted-on
          - source/_patterns/01-atoms/06-section-heading
          - source/_patterns/01-atoms/07-section-content
          - source/_patterns/01-atoms/08-logo
          - source/_patterns/01-atoms/09-social-icons
      molecules:
        paths:
          - source/_patterns/02-molecules/01-blog-tags
          - source/_patterns/02-molecules/02-list-element
          - source/_patterns/02-molecules/03-section
      organisms:
        paths:
          - source/_patterns/03-organisms/01-blog-list
          - source/_patterns/03-organisms/02-header
      #pages:
        #paths:
          #- source/_patterns/04-pages
